# Generated by Django 4.0 on 2023-09-17 22:23

from django.db import migrations, models
import server.models
import server.validators


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to=server.models.category_icon_upload_path),
        ),
        migrations.AddField(
            model_name='channel',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=server.models.server_banner_upload_path, validators=[server.validators.validate_icon_image_size, server.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='server',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
